export const USERME_REQUEST = "USERME_REQUEST";
export const USERME_SUCCESS = "USERME_SUCCESS";
export const USERME_FAILURE = "USERME_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GETUSER_REQUEST = "GETUSER_REQUEST";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_FAILURE = "GETUSER_FAILURE";
export const GETUSER_CLEARDATA = "GETUSER_CLEARDATA";

export const SUBSCRIBE_REQUEST = "SUBSCRIBE_REQUEST";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAILURE = "SUBSCRIBE_FAILURE";

export const GETUSER_ENTRIES_REQUEST = "GETUSER_ENTRIES_REQUEST";
export const GETUSER_ENTRIES_SUCCESS = "GETUSER_ENTRIES_SUCCESS";
export const GETUSER_ENTRIES_FAILURE = "GETUSER_ENTRIES_FAILURE";
export const GETUSER_ENTRIES_CLEAR = "GETUSER_ENTRIES_CLEAR";

export const GETFEED_REQUEST = "GETFEED_REQUEST";
export const GETFEED_SUCCESS = "GETFEED_SUCCESS";
export const GETFEED_FAILURE = "GETFEED_FAILURE";
export const GETFEED_CLEAR = "GETFEED_FAILURE";
export const FEED_READ = "FEED_READ";

export const LIKE_PROFILE_ENTRY_REQUEST = "LIKE_PROFILE_ENTRY_REQUEST";
export const LIKE_PROFILE_ENTRY_SUCCESS = "LIKE_PROFILE_ENTRY_SUCCESS";
export const LIKE_PROFILE_ENTRY_FAILURE = "LIKE_PROFILE_ENTRY_FAILURE";

export const LIKE_FEED_ENTRY_REQUEST = "LIKE_FEED_ENTRY_REQUEST";
export const LIKE_FEED_ENTRY_SUCCESS = "LIKE_FEED_ENTRY_SUCCESS";
export const LIKE_FEED_ENTRY_FAILURE = "LIKE_FEED_ENTRY_FAILURE";

export const API_CHANNEL_CONNECT = "API_CHANNEL_CONNECT";
export const API_CHANNEL_CONNECTED = "API_CHANNEL_CONNECTED";
export const API_CHANNEL_DISCONNECT = "API_CHANNEL_DISCONNECT";
export const API_CHANNEL_DISCONNECTED = "API_CHANNEL_DISCONNECTED";
export const API_CHANNEL_FAILURE = "API_CHANNEL_FAILURE";
export const API_CHANNEL_NEW_ENTRY_PUBLISHED =
  "API_CHANNEL_NEW_ENTRY_PUBLISHED";
export const API_CHANNEL_CONTENT_VOTED = "API_CHANNEL_CONTENT_VOTED";

export const GETENTRY_REQUEST = "GETENTRY_REQUEST";
export const GETENTRY_SUCCESS = "GETENTRY_SUCCESS";
export const GETENTRY_FAILURE = "GETENTRY_FAILURE";
export const GETENTRY_CLEAR = "GETENTRY_CLEAR";

export const LIVE_CHANNEL_CONNECT = "LIVE_CHANNEL_CONNECT";
export const LIVE_CHANNEL_CONNECTED = "LIVE_CHANNEL_CONNECTED";
export const LIVE_CHANNEL_DISCONNECT = "LIVE_CHANNEL_DISCONNECT";
export const LIVE_CHANNEL_DISCONNECTED = "LIVE_CHANNEL_DISCONNECTED";
export const LIVE_CHANNEL_FAILURE = "LIVE_CHANNEL_FAILURE";
export const LIVE_CHANNEL_NEW_COMMENT = "LIVE_CHANNEL_NEW_COMMENT";
export const LIVE_CHANNEL_COMMENT_EDITED = "LIVE_CHANNEL_COMMENT_EDITED";
export const LIVE_CHANNEL_COMMENT_REMOVED = "LIVE_CHANNEL_COMMENT_REMOVED";

export const ENTRYPAGE_COMMENTS_REQUEST = "ENTRYPAGE_COMMENTS_REQUEST";
export const ENTRYPAGE_COMMENTS_SUCCESS = "ENTRYPAGE_COMMENTS_SUCCESS";
export const ENTRYPAGE_COMMENTS_FAILURE = "ENTRYPAGE_COMMENTS_FAILURE";
export const ENTRYPAGE_COMMENTS_CLEAR = "ENTRYPAGE_COMMENTS_CLEAR";

export const ENTRYPAGE_CHANNEL_CONNECT = "ENTRYPAGE_CHANNEL_CONNECT";
export const ENTRYPAGE_CHANNEL_CONNECTED = "ENTRYPAGE_CHANNEL_CONNECTED";
export const ENTRYPAGE_CHANNEL_DISCONNECT = "ENTRYPAGE_CHANNEL_DISCONNECT";
export const ENTRYPAGE_CHANNEL_DISCONNECTED = "ENTRYPAGE_CHANNEL_DISCONNECTED";
export const ENTRYPAGE_CHANNEL_FAILURE = "ENTRYPAGE_CHANNEL_FAILURE";
export const ENTRYPAGE_CHANNEL_COMMENT_CREATED =
  "ENTRYPAGE_CHANNEL_COMMENT_CREATED";
export const ENTRYPAGE_CHANNEL_COMMENT_EDITED =
  "ENTRYPAGE_CHANNEL_COMMENT_EDITED";
export const ENTRYPAGE_CHANNEL_COMMENT_VOTED =
  "ENTRYPAGE_CHANNEL_COMMENT_VOTED";

export const ENTRYPAGE_COMMENT_LIKES_REQUEST =
  "ENTRYPAGE_COMMENT_LIKES_REQUEST";
export const ENTRYPAGE_COMMENT_LIKES_SUCCESS =
  "ENTRYPAGE_COMMENT_LIKES_SUCCESS";
export const ENTRYPAGE_COMMENT_LIKES_FAILURE =
  "ENTRYPAGE_COMMENT_LIKES_FAILURE";

export const GLOBALFETCH_REQUEST = "GLOBALFETCH_REQUEST";
export const GLOBALFETCH_SUCCESS = "GLOBALFETCH_SUCCESS";
export const GLOBALFETCH_FAILURE = "GLOBALFETCH_FAILURE";

export const ENTRYPAGE_VOTE_COMMENT_REQUEST = "ENTRYPAGE_VOTE_COMMENT_REQUEST";
export const ENTRYPAGE_VOTE_COMMENT_SUCCESS = "ENTRYPAGE_VOTE_COMMENT_SUCCESS";
export const ENTRYPAGE_VOTE_COMMENT_FAILURE = "ENTRYPAGE_VOTE_COMMENT_FAILURE";
export const ENTRYPAGE_ADD_COMMENT_REQUEST = "ENTRYPAGE_ADD_COMMENT_REQUEST";
export const ENTRYPAGE_ADD_COMMENT_SUCCESS = "ENTRYPAGE_ADD_COMMENT_SUCCESS";
export const ENTRYPAGE_ADD_COMMENT_FAILURE = "ENTRYPAGE_ADD_COMMENT_FAILURE";
export const ENTRYPAGE_ADD_COMMENT_CLEAR = "ENTRYPAGE_ADD_COMMENT_CLEAR";

export const NOTIFICATIONS_REQUEST = "NOTIFICATIONS_REQUEST";
export const NOTIFICATIONS_SUCCESS = "NOTIFICATIONS_SUCCESS";
export const NOTIFICATIONS_FAILURE = "NOTIFICATIONS_FAILURE";
export const NOTIFICATIONS_COUNT_REQUEST = "NOTIFICATIONS_COUNT_REQUEST";
export const NOTIFICATIONS_COUNT_SUCCESS = "NOTIFICATIONS_COUNT_SUCCESS";
export const NOTIFICATIONS_COUNT_FAILURE = "NOTIFICATIONS_COUNT_FAILURE";
export const NOTIFICATIONS_COUNT_CLEAR = "NOTIFICATIONS_COUNT_CLEAR";

export const PERSONAL_CHANNEL_CONNECTING_REQUEST =
  "PERSONAL_CHANNEL_CONNECTING_REQUEST";
export const PERSONAL_CHANNEL_CONNECTED = "PERSONAL_CHANNEL_CONNECTED";
export const PERSONAL_CHANNEL_CONNECTING_FAILURE =
  "PERSONAL_CHANNEL_CONNECTING_FAILURE";
export const PERSONAL_CHANNEL_DISCONNECTING_REQUEST =
  "PERSONAL_CHANNEL_DISCONNECTING_REQUEST";
export const PERSONAL_CHANNEL_DISCONNECTED = "PERSONAL_CHANNEL_DISCONNECTED";
export const PERSONAL_CHANNEL_LIKE_EVENT = "PERSONAL_CHANNEL_LIKE_EVENT";
export const PERSONAL_CHANNEL_NEW_COMMENT_EVENT =
  "PERSONAL_CHANNEL_NEW_COMMENT_EVENT";
export const PERSONAL_CHANNEL_REPLY_EVENT = "PERSONAL_CHANNEL_REPLY_EVENT";
export const PERSONAL_CHANNEL_MENTION_EVENT = "PERSONAL_CHANNEL_MENTION_EVENT";
export const PERSONAL_CHANNEL_NEW_ENTRY_EVENT =
  "PERSONAL_CHANNEL_NEW_ENTRY_EVENT";
export const PERSONAL_CHANNEL_READ_NOTIFY = "PERSONAL_CHANNEL_READ_NOTIFY";

export const ENTRYPAGE_VOTE_REQUEST = "ENTRYPAGE_VOTE_REQUEST";
export const ENTRYPAGE_VOTE_SUCCESS = "ENTRYPAGE_VOTE_SUCCESS";
export const ENTRYPAGE_VOTE_FAILURE = "ENTRYPAGE_VOTE_FAILURE";
